name: expiration_date
description: "expiration_date"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  dio: ^5.4.0
  easy_localization: ^3.0.3
  liquid_progress_indicator_v2: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/
